name: "Update Assets"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: "scan-virus-ghaction-assets-updater"
  cancel-in-progress: false
jobs:
  update-assets:
    name: "Update Assets"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Get Current Time"
        id: "get-current-time"
        run: |
          Write-Host -Object "::set-output name=time::$(Get-Date -UFormat '%Y-%m-%dT%H:%M:%SZ' -AsUTC)"
        shell: "pwsh"
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          fetch-depth: 0
      - name: "Config Git"
        run: |
          git --no-pager config user.name github-actions
          git --no-pager config user.email github-actions@github.com
        shell: "sh"
      - name: "Invoke Updater"
        run: |
          pwsh -NonInteractive ./assets-updater.ps1
        shell: "sh"
      - name: "Push Git Commit"
        run: |
          git --no-pager add --all
          git --no-pager commit --message="Assets update on ${{steps.get-current-time.outputs.time}}"
          git --no-pager push
        shell: "sh"
