name: "Update Assets"
on:
  schedule:
    - cron: "0 0 * * 0"
    - cron: "0 12 * * 0"
    - cron: "0 0 * * 1"
    - cron: "0 12 * * 1"
    - cron: "0 0 * * 2"
    - cron: "0 12 * * 2"
    - cron: "0 0 * * 3"
    - cron: "0 12 * * 3"
    - cron: "0 0 * * 4"
    - cron: "0 12 * * 4"
    - cron: "0 0 * * 5"
    - cron: "0 12 * * 5"
    - cron: "0 0 * * 6"
    - cron: "0 12 * * 6"
  workflow_dispatch:
    inputs:
      flag:
        description: "{string} Flag."
        required: false
        default: ""
concurrency:
  group: "scan-virus-ghaction-assets-updater"
  cancel-in-progress: false
jobs:
  update-assets:
    name: "Update Assets"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
        with:
          fetch-depth: 0
      - name: "Config Git"
        run: |
          git --no-pager config user.name github-actions
          git --no-pager config user.email github-actions@github.com
        shell: "sh"
      - name: "Invoke Updater"
        id: "updater"
        run: |
          pwsh -NonInteractive ./_updater.ps1
        env:
          INPUT_TRIGGEREDBY: "${{github.event.inputs.flag || github.event.schedule || github.event_name}}"
        shell: "sh"
      - name: "Push Git Commit"
        run: |
          git --no-pager add --all
          git --no-pager commit --message="Update assets on ${{steps.updater.outputs.timestamp}}"
          git --no-pager push
        shell: "sh"
