name: "Update - Assets"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      flags:
        description: "{String[]} Flags."
        required: true
concurrency:
  group: "scan-virus-ghaction-assets-updater"
  cancel-in-progress: false
jobs:
  update-assets:
    name: "Update - Assets"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.4.0"
        with:
          fetch-depth: 0
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@1.1.0"
      - name: "Invoke Updater"
        run: |
          pwsh -NonInteractive ./_updater.ps1
        env:
          INPUT_FLAGS: "${{github.event.inputs.flags}}"
          INPUT_SCHEDULE: "${{github.event.schedule}}"
        shell: "sh"
