# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Update Assets"
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: "update-assets"
  cancel-in-progress: false
jobs:
  main:
    name: "Main"
    permissions:
      contents: "write"
    runs-on: "ubuntu-latest"
    env:
      INPUT_FILES: |-
        .github/**
        clamav/index.tsv
        yara/index.tsv
        .gitattributes
        .gitignore
        README.md
        updater.ps1
    steps:
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@v2.0.0"
        with:
          version: "^2.1.0"
      - name: "Checkout Repository Branch `main`"
        uses: "actions/checkout@v4.1.2"
        with:
          ref: "main"
          fetch-depth: "0"
      - name: "Checkout Repository Branch `base`"
        run: |
          git --no-pager checkout -b base origin/base
      - name: "Switch To Repository Branch `main`"
        run: |
          git --no-pager switch main
      - name: "Config Git"
        run: |
          git --no-pager config --global 'user.name' 'github-actions'
          git --no-pager config --global 'user.email' 'github-actions@users.noreply.github.com'
        shell: "pwsh"
      - name: "Checkout Files From Branch `base` To Branch `main`"
        run: |
          ForEach ($File In (
            $Env:INPUT_FILES -isplit '\r?\n' |
              ForEach-Object -Process { $_.Trim() } |
              Where-Object -FilterScript { $_.Length -gt 0 }
          )) {
            git --no-pager restore --source base -- $File
          }
        shell: "pwsh"
      - name: "Update Assets"
        id: "update-assets"
        run: |
          pwsh -NonInteractive ./updater.ps1
      - name: "Push Repository Branch `main`"
        run: |
          [String]$GitStatus = git --no-pager status --short |
            Join-String -Separator "`n"
          If ($GitStatus.Length -gt 0) {
            git --no-pager add --all
            git --no-pager commit --message="Update assets on ${{steps.update-assets.outputs.timestamp}}"
            git --no-pager push
          }
        shell: "pwsh"
      - name: "Switch To Repository Branch `base`"
        run: |
          git --no-pager switch base
      - name: "Checkout Files From Branch `main` To Branch `base`"
        run: |
          ForEach ($File In (
            $Env:INPUT_FILES -isplit '\r?\n' |
              ForEach-Object -Process { $_.Trim() } |
              Where-Object -FilterScript { $_.Length -gt 0 }
          )) {
            git --no-pager restore --source main -- $File
          }
        shell: "pwsh"
      - name: "Push Repository Branch `base`"
        run: |
          [String]$GitStatus = git --no-pager status --short |
            Join-String -Separator "`n"
          If ($GitStatus.Length -gt 0) {
            git --no-pager add --all
            git --no-pager commit --message="Update assets on ${{steps.update-assets.outputs.timestamp}}"
            git --no-pager push
          }
        shell: "pwsh"
